let handler = m => m

handler.before = function (m) {
    let user = global.db.data.users[m.sender]
    let role = (user.level <= 3) ? 'Merdinha I'
      : ((user.level >= 3) && (user.level <= 6)) ? 'Merdinha II'
      : ((user.level >= 6) && (user.level <= 9)) ? 'Merdinha III'
      : ((user.level >= 9) && (user.level <= 12)) ? 'Merdinha IV'
      : ((user.level >= 12) && (user.level <= 15)) ? 'Merdinha V'
      : ((user.level >= 15) && (user.level <= 18)) ? 'MERDINHA SUPERIOR I'
      : ((user.level >= 18) && (user.level <= 21)) ? 'MERDINHA SUPERIOR II'
      : ((user.level >= 21) && (user.level <= 24)) ? 'MERDINHA SUPERIOR III'
      : ((user.level >= 24) && (user.level <= 27)) ? 'MERDINHA SUPERIOR IV'
      : ((user.level >= 27) && (user.level <= 30)) ? 'MERDINHA SUPERIOR V'
      : ((user.level >= 30) && (user.level <= 33)) ? 'Cabaço I'
      : ((user.level >= 33) && (user.level <= 36)) ? 'Cabaço II'
      : ((user.level >= 36) && (user.level <= 39)) ? 'Cabaço II'
      : ((user.level >= 39) && (user.level <= 42)) ? 'Cabaço IV'
      : ((user.level >= 42) && (user.level <= 45)) ? 'Cabaço V'
      : ((user.level >= 45) && (user.level <= 48)) ? 'Jaguara '
      : ((user.level >= 48) && (user.level <= 51)) ? 'Jaguara Desenvolvido'
      : ((user.level >= 51) && (user.level <= 54)) ? 'Jaguara maior'
      : ((user.level >= 54) && (user.level <= 57)) ? 'Jaguara Mestre'
      : ((user.level >= 57) && (user.level <= 60)) ? 'O Grande Jaguara Supremo'
      : ((user.level >= 60) && (user.level <= 63)) ? 'Juvena Menor'
      : ((user.level >= 63) && (user.level <= 66)) ? 'Juvena Maior'
      : ((user.level >= 66) && (user.level <= 69)) ? 'Pai dos Juvena'
      : ((user.level >= 69) && (user.level <= 71)) ? 'Juvena Mestre'
      : ((user.level >= 71) && (user.level <= 74)) ? 'Juvena Supremo'
      : ((user.level >= 74) && (user.level <= 77)) ? 'Lendário I'
      : ((user.level >= 77) && (user.level <= 80)) ? 'Lendário II'
      : ((user.level >= 80) && (user.level <= 83)) ? 'Lendário III'
      : ((user.level >= 83) && (user.level <= 86)) ? 'Lendário IV'
      : ((user.level >= 86) && (user.level <= 89)) ? 'Lendário V'
      : ((user.level >= 89) && (user.level <= 91)) ? 'Mítico I'
      : ((user.level >= 91) && (user.level <= 94)) ? 'Mítico II'
      : ((user.level >= 94) && (user.level <= 97)) ? 'Mítico III'
      : ((user.level >= 97) && (user.level <= 100)) ? 'Mítico IV'
      : ((user.level >= 100) && (user.level <= 105)) ? 'Mítico V'      
      : ((user.level >= 105) && (user.level <= 120)) ? 'Tu é foda irmão, ta quase nível Spy Uwu'
      : ((user.level >= 120) && (user.level <= 150)) ? 'Esmeralda V'
      : ((user.level >= 150) && (user.level <= 160)) ? 'Esmeralda VI'
      : ((user.level >= 160) && (user.level <= 170)) ? 'Esmeralda III'
      : ((user.level >= 170) && (user.level <= 185)) ? 'Esmeralda II'
      : ((user.level >= 185) && (user.level <= 200)) ? 'Esmeralda I'
      : ((user.level >= 200) && (user.level <= 400)) ? 'Titan III'
      : ((user.level >= 405) && (user.level <= 700)) ? 'Titan II'
      : ((user.level >= 700) && (user.level <= 1000)) ? 'Titan I'
      : 'Dragón rey estellar red, fihotinho do Spy'

    user.role = role
    return true
}

export default handler
